name: nutriguide
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to pub.dev
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# Versioning
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ">=3.5.4 <4.0.0"

# Dependencies specify other packages that your package needs in order to work
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  material_design_icons_flutter: ^6.0.7096
  http: ^1.1.0
  provider: ^6.0.3
  flutter_bloc: ^8.1.2
  linear_progress_bar: ^1.1.2
  numberpicker: ^2.1.2
  image_picker: ^1.0.4
  cloudinary_public: ^0.21.0
  intl: ^0.20.1
  shared_preferences: ^2.2.2
  timeago: ^3.0.2
  app_settings: ^5.1.1
  firebase_messaging: ^15.1.6
  permission_handler: ^10.2.0
  flutter_timezone: ^4.0.0
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^5.3.3
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/landing_page.jpg
    - assets/images/register_page.jpg
    - assets/images/regist_page.jpg
    - assets/images/account-already-registered.png
    - assets/images/double-check-password-email.png
    - assets/images/error-occur.png
    - assets/images/register-success.png
    - assets/images/account-not-registered.png
    - assets/images/no-internet.png
    - assets/images/no-activity.png
    - assets/images/logo_NutriGuide.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
